// Create User
POST http://localhost:5000/user
Content-Type: application/json

{
    "name" : "user",
    "email" : "user@admin.com",
    "password" : "1234",
    "confPassword" : "1234",
    "role" : "user"
}

###
//get All User
GET http://localhost:5000/users

###
//get Single User
GET http://localhost:5000/user/9202983a-4d1c-49e7-becf-21c215ab4c15

###
//Update User
PATCH http://localhost:5000/user/793b1d20-fcdd-4b95-b608-72c419e8e1cf

{
    "name" : "ddd",
    "email" : "Dipouuuudd@gmail.com",
    "password" : "1234",
    "confPassword" : "1234",
    "role" : "user"
}

###
//Delete User
DELETE http://localhost:5000/user/793b1d20-fcdd-4b95-b608-72c419e8e1cf

###
//Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "admin@admin.com",
    "password" : "1234"
}

###
//Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "user@admin.com",
    "password" : "1234"
}

###
//logout
DELETE http://localhost:5000/logout
###
//cek session
GET http://localhost:5000/me

###
//get All Product
GET http://localhost:5000/products

###
//Create Product
POST http://localhost:5000/product
Content-Type: application/json

{
    "name" : "Minyak",
    "price" : 10000
}

###
//get Single Product
GET http://localhost:5000/product/5976520e-b6fe-4054-8a37-d87749c72ff8